"""second: create twit table

Revision ID: 21a3064e221a
Revises: 40f2a5f6060b
Create Date: 2022-06-04 14:00:58.521583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '21a3064e221a'
down_revision = '40f2a5f6060b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twits',
    sa.Column('twit_id', sa.INTEGER(), nullable=False),
    sa.Column('user_name', sa.NVARCHAR(length=100), nullable=False),
    sa.Column('uploaded_on', sa.DateTime(), nullable=True),
    sa.Column('twits', sa.NVARCHAR(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('twit_id')
    )
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.NVARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', mssql.VARBINARY(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__apschedu__3213E83FE89A83CE')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_table('twits')
    # ### end Alembic commands ###
