"""third: add new tables

Revision ID: ffd053d69121
Revises: 21a3064e221a
Create Date: 2022-09-02 02:28:45.739824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'ffd053d69121'
down_revision = '21a3064e221a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_level',
    sa.Column('category_level_id', sa.INTEGER(), nullable=False),
    sa.Column('category_level_name', sa.NVARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('category_level_id')
    )
    op.create_table('industry_group_master',
    sa.Column('industry_grp_id', sa.INTEGER(), nullable=False),
    sa.Column('industry', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('industry_group', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('load_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('industry_grp_id')
    )
    op.create_table('region_master',
    sa.Column('region_id', sa.INTEGER(), nullable=False),
    sa.Column('kearney_reporting_region', sa.NVARCHAR(length=150), nullable=True),
    sa.Column('load_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('region_id')
    )
    op.create_table('supplier_master',
    sa.Column('supplier_id', sa.INTEGER(), nullable=False),
    sa.Column('supplier_name', sa.NVARCHAR(length=500), nullable=True),
    sa.Column('rating', sa.NVARCHAR(length=10), nullable=True),
    sa.Column('is_active', mssql.TINYINT(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('job_id', sa.NVARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_table('category_tree',
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('category_level_id', sa.INTEGER(), nullable=True),
    sa.Column('category_name', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('category_desc', sa.NVARCHAR(length=255), nullable=True),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('is_active', mssql.TINYINT(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_level_id'], ['category_level.category_level_id'], name='FK__category_tree__category_level__category_level_id'),
    sa.ForeignKeyConstraint(['parent_id'], ['category_tree.category_id'], name='FK__category_tree__category_level__parent_id'),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('country',
    sa.Column('country_id', sa.INTEGER(), nullable=False),
    sa.Column('country_code_alpha2', sa.NVARCHAR(length=2), nullable=True),
    sa.Column('country_code_alpha3', sa.NVARCHAR(length=3), nullable=True),
    sa.Column('country', sa.NVARCHAR(length=150), nullable=True),
    sa.Column('region_id', sa.INTEGER(), nullable=True),
    sa.Column('load_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region_master.region_id'], name='FK__country__region_master__region_id'),
    sa.PrimaryKeyConstraint('country_id')
    )
    op.create_table('supplier_additional_attribute',
    sa.Column('supplier_attribute_id', sa.INTEGER(), nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), nullable=False),
    sa.Column('attribute_type', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('attribute_type_subgrouping', sa.NVARCHAR(length=50), nullable=True),
    sa.Column('attribute_name', sa.NVARCHAR(length=20), nullable=True),
    sa.Column('attribute_value', sa.NVARCHAR(length=200), nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), nullable=True),
    sa.Column('is_active', mssql.TINYINT(), nullable=True),
    sa.Column('uploaded_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier_master.supplier_id'], name='FK__supplier_additional_attribute__supplier_master__supplier_id'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], name='FK__supplier_additional_attribute__users__user_id'),
    sa.PrimaryKeyConstraint('supplier_attribute_id')
    )
    op.create_table('supplier_category',
    sa.Column('supplier_category_id', sa.INTEGER(), nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), nullable=False),
    sa.Column('client', sa.NVARCHAR(length=200), nullable=True),
    sa.Column('leaf_category_id', sa.INTEGER(), nullable=True),
    sa.Column('spend_year', sa.INTEGER(), nullable=True),
    sa.Column('spend_usd', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('region_id', sa.INTEGER(), nullable=True),
    sa.Column('country_id', sa.INTEGER(), nullable=True),
    sa.Column('industry_grp_id', sa.INTEGER(), nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), nullable=False),
    sa.Column('is_active', mssql.TINYINT(), nullable=True),
    sa.Column('uploaded_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.country_id'], name='FK__supplier_category__country__country_id'),
    sa.ForeignKeyConstraint(['industry_grp_id'], ['industry_group_master.industry_grp_id'], name='FK__supplier_category__industry_group_master__industry_grp_id'),
    sa.ForeignKeyConstraint(['leaf_category_id'], ['category_tree.category_id'], name='FK__supplier_category__category_tree__leaf_category_id'),
    sa.ForeignKeyConstraint(['region_id'], ['region_master.region_id'], name='FK__supplier_category__region_master__region_id'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier_master.supplier_id'], name='FK__supplier_category__supplier_master__supplier_id'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], name='FK__supplier_category__users__user_id'),
    sa.PrimaryKeyConstraint('supplier_category_id')
    )
    op.create_table('supplier_contact',
    sa.Column('supplier_contact_id', sa.INTEGER(), nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), nullable=False),
    sa.Column('contact_name', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('email_address', sa.NVARCHAR(length=50), nullable=True),
    sa.Column('contact_number', sa.NVARCHAR(length=20), nullable=True),
    sa.Column('designation', sa.NVARCHAR(length=25), nullable=True),
    sa.Column('is_active', mssql.TINYINT(), nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), nullable=True),
    sa.Column('uploaded_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier_master.supplier_id'], name='FK__supplier_contact__supplier_master__supplier_id'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], name='FK__supplier_contact__users__user_id'),
    sa.PrimaryKeyConstraint('supplier_contact_id')
    )
    op.create_table('supplier_metadata',
    sa.Column('supplier_metadata_id', sa.INTEGER(), nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), nullable=False),
    sa.Column('revenue_year', sa.INTEGER(), nullable=True),
    sa.Column('revenue_usd', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('credit_score', sa.INTEGER(), nullable=True),
    sa.Column('diversity_score', sa.INTEGER(), nullable=True),
    sa.Column('supplier_address', sa.NVARCHAR(length=200), nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), nullable=True),
    sa.Column('uploaded_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier_master.supplier_id'], name='FK__supplier_metadata__supplier_master__supplier_id'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], name='FK__supplier_metadata__users__user_id'),
    sa.PrimaryKeyConstraint('supplier_metadata_id')
    )
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.alter_column('twits', 'user_name',
               existing_type=sa.NVARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('twits', 'user_name',
               existing_type=sa.NVARCHAR(length=100),
               nullable=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.NVARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', mssql.VARBINARY(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__apschedu__3213E83FF5747FBF')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_table('supplier_metadata')
    op.drop_table('supplier_contact')
    op.drop_table('supplier_category')
    op.drop_table('supplier_additional_attribute')
    op.drop_table('country')
    op.drop_table('category_tree')
    op.drop_table('supplier_master')
    op.drop_table('region_master')
    op.drop_table('industry_group_master')
    op.drop_table('category_level')
    # ### end Alembic commands ###
